version: '3.5'

services:
  bot:
    build: .
    container_name: rd_bot
    restart: always
    volumes:
      - .env:/root/.env
    networks:
      - app-net

networks:
  app-net:
    external: true
    name: app-net