version: '3.5'

services:
  bot:
    build: .
    container_name: rd_bot
    restart: always
    volumes:
      - .env:/root/.env
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: rd_bot_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
